name: Coverage Test
on:
  workflow_dispatch:
  
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      # Install SFDX
      - name: Install sfdx
        run: npm install --global sfdx-cli
      # Install JQuery
      - name: Install sfdx
        run: npm install jquery
      # Validate Deployment
      - name: Validate Deployment
        run: 'sfdx force:source:deploy -x manifest/package.xml -c -l RunAllTestsInOrg --coverageformatters=json-summary --resultsdir test-results'
      #Write a comment with the Coverage
      - uses: actions/github-script@v5
        with:
          script: |
            coverage=$(cat test-results/coverage/coverage-summary.json | jq -r '.total.lines.pct' )
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Total Coverage: $coverage 🚀'
            })
