name: Coverage Test
on:
  pull_request:
    branches:
      - develop
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.validation.outputs.COVERAGE }}
    steps:
      - uses: actions/checkout@v2
      # Install SFDX
      - name: Install sfdx
        run: npm install --global sfdx-cli
      # Install JQuery
      - name: Install JQuery
        run: npm install jquery
      # Validate Deployment
      - name: Validate Deployment
        id: validation
        run: |
          echo "COVERAGE=$(cat ./test-results/coverage/coverage-summary.json | jq -r '.total.lines.pct' )" >> $GITHUB_OUTPUT
  comment:
    #Write a comment with the Coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: github.event.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Total Coverage: ${{ needs.build.outputs.coverage }} 🚀',
            })
